
SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;


CREATE TABLE `encontradas` (
    `id` INT(5) NOT NULL AUTO_INCREMENT,
	`e_serial` VARCHAR(10),
    `marca` VARCHAR(10) NOT NULL,
    `modelo` VARCHAR(10),
    `color1` VARCHAR(10) NOT NULL,
    `color2` VARCHAR(10),
    `codigo` VARCHAR(10),
    `tipo` VARCHAR(15) NOT NULL,
    `fecha` DATE NOT NULL,
    `lugar` VARCHAR(30) NOT NULL,
    `info_lugar` VARCHAR(100),
    `foto` VARCHAR(255),
    `detalles` VARCHAR(100),
    `email` VARCHAR(20),
    
    
    PRIMARY KEY (`id`),
    UNIQUE KEY `e_serial` (`e_serial`)
)  ENGINE=INNODB DEFAULT CHARSET=LATIN1;


COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
